Suppress error on remove
When I was checking logs I've found that when ptc tries to update cache
because of new avatar the function raises an error about some
non-existent file:

    Traceback (most recent call last):
      File "/var/lib/ptc/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
        resp = await request_handler(request)
      File "/var/lib/ptc/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 537, in _handle
        resp = await handler(request)
      File "/var/lib/ptc/venv/lib/python3.10/site-packages/petthecord/server.py", line 35, in petpet
        return Response(body=await self._petter.petpet(uid), content_type="image/gif")
      File "/var/lib/ptc/venv/lib/python3.10/site-packages/petthecord/cache.py", line 74, in petpet
        remove(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/petthecord/...gif'

Well, I think that it's OK to just suppress the error because GC still
will remove all unneeded files.